ORCHESTRATOR_QUEUE = "orchestrator-queue"
LINUX_QUEUE = "linux-queue"
OPENSTACK_QUEUE = "openstack-queue"

ACTIVITY_GET_PLAN = "get_plan"
ACTIVITY_GET_APPROVAL_STATE = "get_approval_state"
ACTIVITY_START_DEPLOYMENT = "start_deployment"
ACTIVITY_RECORD_ROUND_FACTS = "record_round_facts"
ACTIVITY_FINISH_DEPLOYMENT = "finish_deployment"
ACTIVITY_RESERVE_PLACEMENT = "reserve"
ACTIVITY_ROLLBACK_PLACEMENT = "rollback_reservation"
ACTIVITY_NETWORK_ALLOCATE = "network_allocate"
ACTIVITY_NETWORK_ROLLBACK = "network_rollback"
ACTIVITY_BUILD_ADAPTER_ACTIONS = "build_adapter_actions"
