spring.application.name=placement-service

spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_g3
spring.datasource.username=cloud_admin
spring.datasource.password=cloud_g3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

timefold.solver.termination.spent-limit=2s